---
title: "Search"
output: html_document
date: ""
---

<style type="text/css" rel="stylesheet">
  d-title {
      display: none;
    }
</style>


Last updated `r Sys.Date()`

```{r setup, message = FALSE, warning = FALSE, include = FALSE}
library(dplyr)
library(readr)
library(tidyr)
library(stringr)
library(googledrive)
library(googlesheets4)
library(DT)
library(purrr)
library(lubridate)
library(gargle)
library(data.table)

gs4_deauth()
gs4_auth(token = gargle::secret_read_rds(
  ".secrets/gs4-token.rds",
  key = "GOOGLE_DRIVE_KEY"
))
#gs4_auth(cache = ".secrets", email = "schroejh@bc.edu", scope = "https://www.googleapis.com/auth/drive")
drive_auth(token = gs4_token())

```

```{r, message = FALSE, warning = FALSE, include = FALSE}
# Get file ids from folders
folder_ids <- c("1vsjVWIWOAH1xN8RPvhgmI6ky1vA7CfcJ",
    "145ECofup4M7ZnA1dUF5_pDZN3OWEK1Yb",
    "1gi-k4cgD-XR_AiaSq6J9OPf3OWwkIPCt",
    "1IYkTrGI07fTcjaggY_12V72syNATNSIp",
    "10-NQy1b9lXuXnm5X_FuzYpetI_1PgjOQ",
    "1FbOjmMtKKbgpDou-eyVbhb162RQJMNy-",
    "1LEYANh7PIV9BIC4GpmWByWR4mi2dNtih")

files <- lapply(folder_ids, function(folder) {
  drive_ls(as_id(folder))
})

#Data frame with all files
files <- do.call("rbind", files)
files <- files %>% 
  filter(!(str_detect(name, "TEMPLATE")))

new_files <- files %>% 
  mutate(modifiedTime = map_chr(drive_resource, ~ .x[["modifiedTime"]])) %>%
  mutate(modified_yesterday = ifelse(Sys.time() -as_datetime(modifiedTime) <= 24, TRUE, FALSE)) %>% 
  filter(modified_yesterday == TRUE)
```

```{r, message = FALSE, warning = FALSE, include = FALSE}
# Get the master sheet from each file
sheet <- "master"
lookup <- c(persTitle = "personTitle", persTitle = "title", instID = 0, instID = "ros", attendingInstID = "attendingIstD", attendingInstID = "attendingChurchID", attendingInstID = "AttendingChurchID")
not_these <- c("", "temp")

time1 <- Sys.time()
master <- data.frame("instID" = NA, "type" = NA, "instName" = NA, "language" = NA, "instNote" = NA, "placeName" = NA, "region" = NA, "county_orig" = NA, "county_reg"   = NA, "city_orig" = NA, "city_reg" = NA, "state_orig" = NA, "state_reg" = NA, "latitude" = NA, "longitude" = NA, "attendingInstID" = NA, "attendingChurch" = NA, "attendingChurchFrequency" = NA, "attendingChurchNote" = NA, "persID" = NA, "persTitle" = NA, "persName" = NA, "persSuffix" = NA, "persRole" = NA, "persNote"      = NA, "memberType" = NA, "member" = NA, "affiliated" = NA, "diocese" = NA, "year" = NA)
no_rows_sheets <- NULL
problem_sheets <- NULL

for (i in 1:nrow(files)) {
  warning(print(paste0("trying ", files$name[i])))
  tryCatch(
    {
    sheet_master <- read_sheet(files$id[i], sheet = sheet) %>%
       mutate(diocese = str_extract(files$name[i], "[A-Za-z]+"),
              year = str_extract(files$name[i], "\\d+"),
              file_id = files$id[i]) %>%
      rename(any_of(lookup)) %>%
      mutate(across(everything(), as.character), 
             city_reg = ifelse(is.na(city_reg), "none", city_reg), 
             state_reg = ifelse(is.na(state_reg), "none", state_reg)) %>%
      select(-any_of(not_these))
    
    print(paste0(files$name[i], " went through the cleaning!"))
    
     if(nrow(sheet_master) != 0) {
      master <- bind_rows(sheet_master, master)
       print(paste0("we bound the rows of ", files$name[i], " (", nrow(sheet_master), " rows)"))
       
      } else {
       no_rows_sheets <- c(no_rows_sheets, files$id[i])
       print(paste0(files$name[i], " has no rows"))
  
      }
  },
  error = function(e) {
    problem_sheets <- c(problem_sheets, files$id[i])
    warning(paste0(files$name[i], " is giving us trouble!"))
    
  })
  
  Sys.sleep(5)
}

time2 <- Sys.time()

print(time2-time1)
master <- master %>% select(1:32)
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
fwrite(master, "./_data/master.csv.gz")

#Inst info
master_inst <- master %>% select(c(1:6, 29:30)) %>%
  fill(instID, .direction = "down") %>% distinct() %>%
  filter_at(vars(type, instName, language, instNote,
                 placeName), any_vars(!is.na(.)))

#Inst geo info
master_geo <- master %>% select(c(1, 7:15, 29:30)) %>% 
  mutate(city_reg = ifelse(city_reg == "none", NA, city_reg),
         state_reg = ifelse(state_reg == "none", NA, state_reg)) %>%
  fill(instID, .direction = "down") %>% distinct() %>%
  filter_at(vars(region, county_orig, county_reg, city_orig, city_reg,
                 state_orig, state_reg, latitude, longitude),
            any_vars(!is.na(.)))

#Attending info
master_att <- master %>% select(c(1, 16:19, 29:30)) %>%
  fill(instID, .direction = "down") %>% distinct() %>%
  filter_at(vars(attendingInstID, attendingChurch,
                 attendingChurchFrequency, attendingChurchNote),
            any_vars(!is.na(.)))

#Person info
master_pers <- master %>% select(c(1, 20:28, 29:30)) %>% 
  fill(instID, .direction = "down") %>% distinct() %>%
  filter_at(vars(persID, persTitle, persName, persSuffix, persRole,
                 persNote, memberType, member, affiliated),
            any_vars(!is.na(.))) %>%
  filter(!is.na(persID))
```

# Institution Information

```{r, echo = FALSE, warning = FALSE, message = FALSE}
datatable(master_inst, rownames= FALSE,
          options = list(searchHighlight = TRUE),
          filter = list(position = 'top', clear = FALSE,
                                     rownames= FALSE))
```

# Institution Geographic Information


```{r, echo = FALSE, warning = FALSE, message = FALSE}
datatable(master_geo, rownames= FALSE,
          options = list(searchHighlight = TRUE),
          filter = list(position = 'top', clear = FALSE,
                                    rownames= FALSE))
```

# Institution Attending Information

```{r, echo = FALSE, warning = FALSE, message = FALSE}
datatable(master_att, rownames= FALSE,
          options = list(searchHighlight = TRUE),
          filter = list(position = 'top', clear = FALSE,
                                    rownames= FALSE))
```

# Institution Person Information

```{r, echo = FALSE, warning = FALSE, message = FALSE}
datatable(master_pers, rownames= FALSE,
          options = list(searchHighlight = TRUE),
          filter = list(position = 'top', clear = FALSE,
                                     rownames= FALSE))
```

# FYI
```{r, warning = FALSE, echo = FALSE}
no_rows <- files %>% filter(id %in% no_rows_sheets) %>% pull(name)
problems <- files %>% filter(id %in% problem_sheets) %>% pull(name)

if(length(no_rows) != 0) {
  message(paste0("These sheets are empty: ", print(no_rows)))
} else {
  message(paste0("No sheets are empty!"))
}

if(length(problems) != 0) {
  message(paste0("These sheets are giving us problems: ", print(problems))) 
} else {
  message(paste0("No sheets are giving us problems!"))
}

```




```{r, include = FALSE, eval = FALSE}
# Get the peopleInfo sheet from each file
sheet <- "master"

time1 <- Sys.time()
masterCols <- data.frame()

masterCols <- read_sheet(files$id[1], sheet = sheet) %>% colnames() %>% data.frame()
colnames(masterCols) <- files$name[1]

for (i in 2:nrow(files)) {
   
  tryCatch(
    {
      masterCols_sheet <- read_sheet(files$id[i], sheet = sheet) %>% colnames() %>%
        data.frame()
      colnames(masterCols_sheet) <- files$name[i]
      masterCols <- bind_cols(masterCols, masterCols_sheet)
  },
  error = function(e) {
    message("Something didn't work right!")
  })
  
}

time2 <- Sys.time()
print(time2-time1)
#write_csv(peopleInfos, "peopleInfos.csv")
#getwd()

columns <- t(masterCols) %>% as.data.frame()
unique(columns$V29)

columns %>% filter(V21 == "personTitle")

write.csv(columns, "columns.csv")


```

```{r, eval = FALSE, message = FALSE, warning = FALSE, include = FALSE}
# Get the master sheet from each file
sheet <- "master"
lookup <- c(persTitle = "personTitle", persTitle = "title", instID = 0, instID = "ros", attendingInstID = "attendingIstD", attendingInstID = "attendingChurchID", attendingInstID = "AttendingChurchID")
not_these <- c("", "temp")

time1 <- Sys.time()
master <- data.frame("instID" = NA, "type" = NA, "instName" = NA, "language" = NA, "instNote" = NA, "placeName" = NA, "region" = NA, "county_orig" = NA, "county_reg"   = NA, "city_orig" = NA, "city_reg" = NA, "state_orig" = NA, "state_reg" = NA, "latitude" = NA, "longitude" = NA, "attendingInstID" = NA, "attendingChurch" = NA, "attendingChurchFrequency" = NA, "attendingChurchNote" = NA, "persID" = NA, "persTitle" = NA, "persName" = NA, "persSuffix" = NA, "persRole" = NA, "persNote"      = NA, "memberType" = NA, "member" = NA, "affiliated" = NA, "diocese" = NA, "year" = NA)
problem_sheets <- NULL

for (i in 1:nrow(new_files)) {
   
  tryCatch(
    {
    sheet_master <- read_sheet(new_files$id[i], sheet = sheet) %>%
       mutate(diocese = str_extract(new_files$name[i], "[A-Za-z]+"),
              year = str_extract(new_files$name[i], "\\d+"),
              file_id = new_files$id[i]) %>%
      rename(any_of(lookup)) %>%
      mutate(across(everything(), as.character),
             city_reg = ifelse(is.na(city_reg), "none", city_reg), 
             state_reg = ifelse(is.na(state_reg), "none", state_reg)) %>%
      select(-any_of(not_these))
    print(new_files$id[i])
    print(nrow(sheet_master))
     if(nrow(sheet_master) != 0) {
      master <- bind_rows(sheet_master, master)
      }
     else {
       problem_sheets <- c(problem_sheets,new_files$id[i])
       next
      }
  },
  error = function(e) {
    problem_sheets <- c(problem_sheets,new_files$id[i])
    message("Something didn't work right!")
  })
  
}

time2 <- Sys.time()

print(time2-time1)
master_new <- master %>% select(1:32)

# Making Tables
master <- fread("./_data/master.csv.gz") %>% mutate(across(everything(), as.character)) %>% filter(!(file_id %in% new_files$id)) %>% bind_rows(master_new) %>% mutate_all(list(~na_if(.,"")))
```