---
title: "update_formulas"
output: html_document
date: "2025-01-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readr)
library(tidyr)
library(stringr)
library(googledrive)
library(googlesheets4)
library(DT)
library(purrr)
library(lubridate)
library(gargle)
library(diffdf)

gs4_deauth()
#gs4_auth(token = gargle::secret_read_rds(
#  ".secrets/gs4-token.rds",
#  key = "GOOGLE_DRIVE_KEY"
#))
gs4_auth(cache = ".secrets", email = "schroejh@bc.edu", scope = "https://www.googleapis.com/auth/drive")
drive_auth(token = gs4_token())

folder_ids <- c("1vsjVWIWOAH1xN8RPvhgmI6ky1vA7CfcJ",
                "145ECofup4M7ZnA1dUF5_pDZN3OWEK1Yb",
                "1gi-k4cgD-XR_AiaSq6J9OPf3OWwkIPCt",
                "1IYkTrGI07fTcjaggY_12V72syNATNSIp",
                "10-NQy1b9lXuXnm5X_FuzYpetI_1PgjOQ",
                "1FbOjmMtKKbgpDou-eyVbhb162RQJMNy-",
                "1LEYANh7PIV9BIC4GpmWByWR4mi2dNtih")

files <- lapply(folder_ids, function(folder) {
  drive_ls(as_id(folder))
})
files <- do.call("rbind", files) 
files <- files %>% filter(!(str_detect(name, "TEMPLATE")))

```

# Add year and diocese to all sheets 

```{r}
for(i in 1:nrow(files)){
        year <- as.numeric(str_extract(files$name[i], "\\d+"))
        place <- str_extract(files$name[i], "[A-Za-z]+")
 # WRITE YEARS
        range_write(files$id[i], 
                   data.frame(year),
                   sheet = "master",
                   range = "AC2",
                   col_names = FALSE,
                   reformat = FALSE)
        range_write(files$id[i], 
                    data.frame("year"),
                    sheet = "master",
                    range = "AC1",
                    col_names = FALSE,
                    reformat = FALSE)
 # WRITE DIOCESE
        range_write(files$id[i], 
                    data.frame(place),
                    sheet = "master",
                    range = "AD2",
                    col_names = FALSE,
                    reformat = FALSE)
        range_write(files$id[i], 
                    data.frame("diocese"),
                    sheet = "master",
                    range = "AD1",
                    col_names = FALSE,
                    reformat = FALSE)
      }
```

# Add new formulas 

```{r}
for(i in 1:nrow(files)){
  nrows <- as.numeric(nrow(range_read(files$id[i])))
  
  formulas <- paste0('=ARRAYFORMULA(XLOOKUP(peopleInfo!K', 2:nrows , ' & master!AD$2 & master!AC$2,
  IMPORTRANGE("10rvRUGe4br313NCdOI7saxbwb9xmuY5OyOZkFojPk2k", "personIDs!A:A") & 
  IMPORTRANGE("10rvRUGe4br313NCdOI7saxbwb9xmuY5OyOZkFojPk2k", "personIDs!B:B") & 
  IMPORTRANGE("10rvRUGe4br313NCdOI7saxbwb9xmuY5OyOZkFojPk2k", "personIDs!C:C"),
  IMPORTRANGE("10rvRUGe4br313NCdOI7saxbwb9xmuY5OyOZkFojPk2k", "personIDs!E:E"), ""))')
  
  formula <- as.data.frame(list(formula = formulas)) 
  formula$formula <- gs4_formula(formula$formula)
  
  #range_delete(files$id[i], 
  #             sheet = "peopleInfo", 
  #             cell_cols("M:O"), 
  #             shift = NULL)

  range_write(files$id[i], 
              data = formula,
              sheet = "peopleInfo",
              range = paste0("L2:L", nrows),
              col_names = FALSE,
              reformat = FALSE)
}

```

```{r}
for(i in 1:nrow(files)){
  
 # peopleInfo <- range_read(files$id[i], 
#               sheet = "peopleInfo", 
#               range = "A1")

  peopleIDs <- range_read(files$id[i], 
               sheet = "peopleInfo", 
               range = "B2")
  
 # print(colnames(peopleInfo))
  print(colnames(peopleIDs))  
}
```


```{r}
for(i in 139:nrow(files)){
  
  nrows <- as.numeric(nrow(range_read(files$id[i])))
  
    formulas <- paste0('=ARRAYFORMULA(XLOOKUP(peopleInfo!K', 2:nrows , ' & master!AD$2 & master!AC$2,
  IMPORTRANGE("10rvRUGe4br313NCdOI7saxbwb9xmuY5OyOZkFojPk2k", "personIDs!A:A") & 
  IMPORTRANGE("10rvRUGe4br313NCdOI7saxbwb9xmuY5OyOZkFojPk2k", "personIDs!B:B") & 
  IMPORTRANGE("10rvRUGe4br313NCdOI7saxbwb9xmuY5OyOZkFojPk2k", "personIDs!C:C"),
  IMPORTRANGE("10rvRUGe4br313NCdOI7saxbwb9xmuY5OyOZkFojPk2k", "personIDs!E:E"), ""))')
  
  formula <- as.data.frame(list(formula = formulas)) 
  formula$formula <- gs4_formula(formula$formula)

  # peopleInfo
  # Delete peopleInfo!A
  
  range_delete(files$id[i], 
            sheet = "peopleInfo", 
            range = "A:A")
  
F2 <- data.frame(form = '=ARRAYFORMULA(LOWER(REGEXREPLACE(REGEXREPLACE(B2:B, "[[:punct:]-—]", ""), "\b(Von|De|La|Der|Van|von|de|la|der|van)\\s+(\\w+)", "$1-$2")))')
G2 <- data.frame(form = '=ARRAYFORMULA(IFERROR(REGEXEXTRACT(F2:F, "\\s(\\S+)$"), F2:F))')
H2 <- data.frame(form = '=ARRAYFORMULA(IF(LEN(F2:F) - LEN(SUBSTITUTE(F2:F, " ", "")) = 0, , IFERROR(REGEXEXTRACT(F2:F, "^(.*)\\s\\S+$"), F2:F)))')
I2 <- data.frame(form = '=ARRAYFORMULA(IFERROR(REGEXEXTRACT(H2:H, "^\\S+"), H2:H))')
J2 <- data.frame(form = '=ARRAYFORMULA(IFERROR(REGEXEXTRACT(H2:H, "^\\S+\\s(.*)"), ""))')
K2 <- data.frame(form = '=ARRAYFORMULA(
  SUBSTITUTE(
    IF( 
      REGEXMATCH(A2:A, "(Sister|Mother|OtherException|Brother|Bro.)") +
      REGEXMATCH(B2:B, "(Brother|Sister|Ladies)") +
      (ISBLANK(I2:I) * ISBLANK(G2:G)),
      "",
      IF(
        ISBLANK(I2:I),
        G2:G,
        IF(
          LEN(I2:I) >= 3,
          IF(
            ISBLANK(J2:J),
            LEFT(I2:I, 3) & "_" & G2:G,
            LEFT(I2:I, 3) & "_" & LEFT(J2:J, 1) & "_" & G2:G
          ),
          IF(
            LEN(I2:I) = 2,
            IF(
              ISBLANK(J2:J),
              LEFT(I2:I, 2) & "_" & G2:G,
              LEFT(I2:I, 2) & "_" & LEFT(J2:J, 1) & "_" & G2:G
            ),
            IF(
              LEN(I2:I) = 1,
              IF(
                ISBLANK(J2:J),
                LEFT(I2:I, 1) & "_" & G2:G,
                LEFT(I2:I, 1) & "_" & LEFT(J2:J, 1) & "_" & G2:G
              ),
              ""
            )
          )
        )
      )
    ),
    "__", "_"
  )
)')

F2$form <- gs4_formula(F2$form) 
G2$form <- gs4_formula(G2$form) 
H2$form <- gs4_formula(H2$form) 
I2$form <- gs4_formula(I2$form) 
J2$form <- gs4_formula(J2$form) 
K2$form <- gs4_formula(K2$form) 

  range_write(files$id[i], 
            F2,
            sheet = "peopleInfo",
            range = "F2",
            col_names = FALSE,
            reformat = FALSE)
  
  range_write(files$id[i], 
            G2,
            sheet = "peopleInfo",
            range = "G2",
            col_names = FALSE,
            reformat = FALSE)
  
    range_write(files$id[i], 
            H2,
            sheet = "peopleInfo",
            range = "H2",
            col_names = FALSE,
            reformat = FALSE)
    
    range_write(files$id[i], 
            I2,
            sheet = "peopleInfo",
            range = "I2",
            col_names = FALSE,
            reformat = FALSE)
  
    range_write(files$id[i], 
            J2,
            sheet = "peopleInfo",
            range = "J2",
            col_names = FALSE,
            reformat = FALSE)
    
    range_write(files$id[i], 
            K2,
            sheet = "peopleInfo",
            range = "K2",
            col_names = FALSE,
            reformat = FALSE)
  
    range_write(files$id[i], 
              data = formula,
              sheet = "peopleInfo",
              range = paste0("L2:L", nrows),
              col_names = FALSE,
              reformat = FALSE)
  
  # need to also update the other formulas
  
  # peopleIDs
  # A = (persName) =peopleInfo!C:C
  # B = (persID_gen) =peopleInfo!M:M
  # C = (persID_cor)
  # D = (persID) =IF(C2="",B2,C2)
  
  col1 <- c("persName", "persID_gen", "persID_cor", "persID")
  #col2 <- c("=peopleInfo!C:C", "=peopleInfo!M:M", "", 'IF(C2="",B2,C2)')
  
  df <- as.data.frame(list(col1 = col1)) 
  df <- t(df)
  
   range_write(files$id[i], 
               data.frame(df),
               sheet = "peopleIDs",
               range = "A1:D1",
               col_names = FALSE,
               reformat = FALSE)
   
  A2 <- data.frame(form = rep('=peopleInfo!B:B', (nrows-1)))
  B2 <- data.frame(form = rep('=peopleInfo!L:L', (nrows-1)))
  D2 <- data.frame(form = paste0('=IF(C', 2:nrows, '="",B', 2:nrows, ',C', 2:nrows, ')')) 
   
  A2$form <- gs4_formula(A2$form) 
  B2$form <- gs4_formula(B2$form) 
  D2$form <- gs4_formula(D2$form) 

  range_write(files$id[i], 
            A2,
            sheet = "peopleIDs",
            range = paste0("A2:A", nrows),
            col_names = FALSE,
            reformat = FALSE)
  
  range_write(files$id[i], 
            B2,
            sheet = "peopleIDs",
            range = paste0("B2:B", nrows),
            col_names = FALSE,
            reformat = FALSE)
  
  range_clear(files$id[i], 
              sheet = "peopleIDs", 
              range = paste0("C2:C", nrows), 
              reformat = TRUE)
  
    
    range_write(files$id[i], 
            D2,
            sheet = "peopleIDs",
            range = "D2",
            col_names = FALSE,
            reformat = FALSE)
  
  # master
  # T = (persID) =peopleIDs!T:T

    T2 <- data.frame(form = rep('=peopleIDs!D:D', (nrows-1)))
    T2$form <- gs4_formula(T2$form) 

  range_write(files$id[i], 
              T2,
              sheet = "master",
              range = paste0("T2:T", nrows),
              col_names = FALSE,
              reformat = FALSE)
}

```

```{r}
for(i in 139:nrow(files)){
 # peopleInfo <- range_read(files$id[i], 
#               sheet = "peopleInfo", 
#               range = "A1")
  
 #   tryCatch(
#    {

    #    range_write(files$id[i], 
    #               data.frame("initialID"),
    #               sheet = "peopleInfo",
    #               range = "K1",
    #               col_names = FALSE,
    #               reformat = FALSE)
    #    range_write(files$id[i], 
    #                data.frame("persID_gen"),
    #                sheet = "peopleInfo",
    #                range = "L1",
    #                col_names = FALSE,
    #                reformat = FALSE)

  peopleIDs <- range_read(files$id[i], 
               sheet = "peopleInfo", 
               range = "K:K") %>% 
    mutate(wrong = str_detect(initialID, "\b(\\w{3})_\1\b")) %>%
    filter(wrong == TRUE)
  
  #print(colnames(peopleInfo))
  if (nrow(peopleIDs != 0)) {
  print(peopleIDs) }
  else next
    }#,
  #    error = function(e) {
  #      message("This sheet needs column names!")
  #    })
  
#}

```


```{r}
#for(i in 1:nrow(files)){
 
  i = 1
  
  nrows <- as.numeric(nrow(range_read(files$id[i])))

A_persTitle <- rep('=master!U:U', nrows - 1)
A_persTitle <- as.data.frame(list(form = A_persTitle)) 
B_persName <- rep('=master!V:V', nrows - 1)
B_persName <- as.data.frame(list(form = B_persName)) 
C_persSuffix <- rep('=master!W:W', nrows - 1)  
C_persSuffix <- as.data.frame(list(form = C_persSuffix)) 
D_persRole <- rep('=master!X:X', nrows - 1) 
D_persRole <- as.data.frame(list(form = D_persRole)) 
E_persNote <- rep('=master!Y:Y', nrows - 1) 
E_persNote <- as.data.frame(list(form = E_persNote)) 

F_persName_clean <- '=ARRAYFORMULA(LOWER(REGEXREPLACE(REGEXREPLACE(REGEXREPLACE(B2:B, "[[:punct:]-—]", ""), "\\b(Von|De|La|Der|Van|von|de|la|der|van)\\s+(\\w+)", "$1-$2"), "^\\s", "")))'
F_persName_clean <- as.data.frame(list(form = F_persName_clean)) 

G_lastName <- '=ARRAYFORMULA(IFERROR(REGEXEXTRACT(F2:F, "\\s(\\S+)$"), F2:F))'
G_lastName <- as.data.frame(list(form = G_lastName)) 

H_firstMiddle <- '=ARRAYFORMULA(IF(LEN(F2:F) - LEN(SUBSTITUTE(F2:F, " ", "")) = 0, , IFERROR(REGEXEXTRACT(F2:F, "^(.*)\\s\\S+$"), F2:F)))'
H_firstMiddle <- as.data.frame(list(form = H_firstMiddle)) 

I_firstName <- '=ARRAYFORMULA(IFERROR(REGEXEXTRACT(H2:H, "^\\S+"), H2:H))'
I_firstName <- as.data.frame(list(form = I_firstName)) 

J_middleName <- '=ARRAYFORMULA(IFERROR(REGEXEXTRACT(H2:H, "^\\S+\\s(.*)"), ""))'
J_middleName <- as.data.frame(list(form = J_middleName)) 

K_initialID <- data.frame(form = '=ARRAYFORMULA(
  SUBSTITUTE(
    IF( 
      REGEXMATCH(A2:A, "(Sister|Mother|OtherException|Brother|Bro.|Sœur|Soeur|Madame|Madam)") +
      REGEXMATCH(B2:B, "(Brother|Sister|Ladies|Sœur|Soeur|Madame|Madam)") +
      (ISBLANK(I2:I) * ISBLANK(G2:G)),
      "",
      IF(
        ISBLANK(I2:I),
        G2:G,
        IF(
          LEN(I2:I) >= 3,
          IF(
            ISBLANK(J2:J),
            LEFT(I2:I, 3) & "_" & G2:G,
            LEFT(I2:I, 3) & "_" & LEFT(J2:J, 1) & "_" & G2:G
          ),
          IF(
            LEN(I2:I) = 2,
            IF(
              ISBLANK(J2:J),
              LEFT(I2:I, 2) & "_" & G2:G,
              LEFT(I2:I, 2) & "_" & LEFT(J2:J, 1) & "_" & G2:G
            ),
            IF(
              LEN(I2:I) = 1,
              IF(
                ISBLANK(J2:J),
                LEFT(I2:I, 1) & "_" & G2:G,
                LEFT(I2:I, 1) & "_" & LEFT(J2:J, 1) & "_" & G2:G
              ),
              ""
            )
          )
        )
      )
    ),
    "__", "_"
  )
)')

    L_persID_gen <- paste0('=ARRAYFORMULA(XLOOKUP(peopleInfo!K', 2:nrows , ' & master!AD$2 & master!AC$2,
  IMPORTRANGE("10rvRUGe4br313NCdOI7saxbwb9xmuY5OyOZkFojPk2k", "personIDs!A:A") & 
  IMPORTRANGE("10rvRUGe4br313NCdOI7saxbwb9xmuY5OyOZkFojPk2k", "personIDs!B:B") & 
  IMPORTRANGE("10rvRUGe4br313NCdOI7saxbwb9xmuY5OyOZkFojPk2k", "personIDs!C:C"),
  IMPORTRANGE("10rvRUGe4br313NCdOI7saxbwb9xmuY5OyOZkFojPk2k", "personIDs!E:E"), ""))')
  
  formula <- as.data.frame(list(formula = L_persID_gen)) 
  formula$formula <- gs4_formula(formula$formula)

A_persTitle$form <- gs4_formula(A_persTitle$form) 
B_persName$form <- gs4_formula(B_persName$form) 
C_persSuffix$form <- gs4_formula(C_persSuffix$form) 
D_persRole$form <- gs4_formula(D_persRole$form) 
E_persNote$form <- gs4_formula(E_persNote$form) 
F_persName_clean$form <- gs4_formula(F_persName_clean$form) 
G_lastName$form <- gs4_formula(G_lastName$form) 
H_firstMiddle$form <- gs4_formula(H_firstMiddle$form) 
I_firstName$form <- gs4_formula(I_firstName$form) 
J_middleName$form <- gs4_formula(J_middleName$form) 
K_initialID$form <- gs4_formula(K_initialID$form) 

  range_write(files$id[i], 
            A_persTitle,
            sheet = "peopleInfo",
            range = paste0("A2:A", nrows),
            col_names = FALSE,
            reformat = FALSE)
  
  range_write(files$id[i], 
            B_persName,
            sheet = "peopleInfo",
            range = paste0("B2:B", nrows),
            col_names = FALSE,
            reformat = FALSE)
  
    range_write(files$id[i], 
            C_persSuffix,
            sheet = "peopleInfo",
            range = paste0("C2:C", nrows),
            col_names = FALSE,
            reformat = FALSE)
    
    range_write(files$id[i], 
            D_persRole,
            sheet = "peopleInfo",
            range = paste0("D2:D", nrows),
            col_names = FALSE,
            reformat = FALSE)
  
    range_write(files$id[i], 
            E_persNote,
            sheet = "peopleInfo",
            range = paste0("E2:E", nrows),
            col_names = FALSE,
            reformat = FALSE)
    
    range_write(files$id[i], 
            F_persName_clean,
            sheet = "peopleInfo",
            range = "F2",
            col_names = FALSE,
            reformat = FALSE)
  
    range_write(files$id[i], 
            G_lastName,
            sheet = "peopleInfo",
            range = "G2",
            col_names = FALSE,
            reformat = FALSE)
    
    range_write(files$id[i], 
            H_firstMiddle,
            sheet = "peopleInfo",
            range = "H2",
            col_names = FALSE,
            reformat = FALSE)
    
        range_write(files$id[i], 
            I_firstName,
            sheet = "peopleInfo",
            range = "I2",
            col_names = FALSE,
            reformat = FALSE)
        
        range_write(files$id[i], 
            J_middleName,
            sheet = "peopleInfo",
            range = "J2",
            col_names = FALSE,
            reformat = FALSE)
        
        range_write(files$id[i], 
            K_initialID,
            sheet = "peopleInfo",
            range = "K2",
            col_names = FALSE,
            reformat = FALSE)
        
        range_write(files$id[i], 
            formula,
            sheet = "peopleInfo",
            range = paste0("L2:L", nrows),
            col_names = FALSE,
            reformat = FALSE)
  
#}

```

```{r}
for(i in 1:nrow(files)){
 
  peopleInfo <- range_read(files$id[i], 
                sheet = "peopleInfo") %>%
    filter(str_detect(persID_gen, '#REF!'))
  
  if(nrow(peopleInfo) > 0) {
    
    print("REFs here!")
    
  } 
  else next

}

  #}
  
```


```{r}
for(i in 1:nrow(files)){
  
 # peopleInfo <- range_read(files$id[i], 
#               sheet = "peopleInfo", 
#               range = "A1")

  peopleIDs <- range_read(files$id[i], 
               sheet = "peopleInfo", 
               range = "B2")
  
 # print(colnames(peopleInfo))
  print(colnames(peopleIDs))  
}
```


```{r}
for(i in 145:nrow(files)){
 
#  i = 3
  
  nrows = 1000

A_persTitle <- rep('=master!U:U', nrows - 1)
A_persTitle <- as.data.frame(list(form = A_persTitle)) 
B_persName <- rep('=master!V:V', nrows - 1)
B_persName <- as.data.frame(list(form = B_persName)) 
C_persSuffix <- rep('=master!W:W', nrows - 1)  
C_persSuffix <- as.data.frame(list(form = C_persSuffix)) 
D_persRole <- rep('=master!X:X', nrows - 1) 
D_persRole <- as.data.frame(list(form = D_persRole)) 
E_persNote <- rep('=master!Y:Y', nrows - 1) 
E_persNote <- as.data.frame(list(form = E_persNote)) 

    L_persID_gen <- paste0('=ARRAYFORMULA(XLOOKUP(peopleInfo!K', 2:nrows , ' & master!AD$2 & master!AC$2,
  IMPORTRANGE("10rvRUGe4br313NCdOI7saxbwb9xmuY5OyOZkFojPk2k", "personIDs!A:A") & 
  IMPORTRANGE("10rvRUGe4br313NCdOI7saxbwb9xmuY5OyOZkFojPk2k", "personIDs!B:B") & 
  IMPORTRANGE("10rvRUGe4br313NCdOI7saxbwb9xmuY5OyOZkFojPk2k", "personIDs!C:C"),
  IMPORTRANGE("10rvRUGe4br313NCdOI7saxbwb9xmuY5OyOZkFojPk2k", "personIDs!E:E"), ""))')

A_persTitle$form <- gs4_formula(A_persTitle$form) 
B_persName$form <- gs4_formula(B_persName$form) 
C_persSuffix$form <- gs4_formula(C_persSuffix$form) 
D_persRole$form <- gs4_formula(D_persRole$form) 
E_persNote$form <- gs4_formula(E_persNote$form) 

formula <- as.data.frame(list(formula = L_persID_gen)) 
formula$formula <- gs4_formula(formula$formula)

  range_write(files$id[i], 
            A_persTitle,
            sheet = "peopleInfo",
            range = paste0("A2:A", nrows),
            col_names = FALSE,
            reformat = FALSE)
  
  range_write(files$id[i], 
            B_persName,
            sheet = "peopleInfo",
            range = paste0("B2:B", nrows),
            col_names = FALSE,
            reformat = FALSE)
  
    range_write(files$id[i], 
            C_persSuffix,
            sheet = "peopleInfo",
            range = paste0("C2:C", nrows),
            col_names = FALSE,
            reformat = FALSE)
    
    range_write(files$id[i], 
            D_persRole,
            sheet = "peopleInfo",
            range = paste0("D2:D", nrows),
            col_names = FALSE,
            reformat = FALSE)
  
    range_write(files$id[i], 
            E_persNote,
            sheet = "peopleInfo",
            range = paste0("E2:E", nrows),
            col_names = FALSE,
            reformat = FALSE)
    
        
        range_write(files$id[i], 
            formula,
            sheet = "peopleInfo",
            range = paste0("L2:L", nrows),
            col_names = FALSE,
            reformat = FALSE)

  A2 <- data.frame(form = rep('=peopleInfo!B:B', (nrows-1)))
  B2 <- data.frame(form = rep('=peopleInfo!L:L', (nrows-1)))
  D2 <- data.frame(form = paste0('=IF(C', 2:nrows, '="",B', 2:nrows, ',C', 2:nrows, ')')) 
     
  A2$form <- gs4_formula(A2$form) 
  B2$form <- gs4_formula(B2$form) 
  D2$form <- gs4_formula(D2$form) 

  range_write(files$id[i], 
            A2,
            sheet = "peopleIDs",
            range = paste0("A2:A", nrows),
            col_names = FALSE,
            reformat = FALSE)
  
  range_write(files$id[i], 
            B2,
            sheet = "peopleIDs",
            range = paste0("B2:B", nrows),
            col_names = FALSE,
            reformat = FALSE)
  
    range_write(files$id[i], 
            D2,
            sheet = "peopleIDs",
            range = "D2",
            col_names = FALSE,
            reformat = FALSE)
  
  
}

```

```{r}
info <- NULL
for(i in 1:nrow(files)){
  
  #i = 1
  
  #year <- as.numeric(str_extract(files$name[i], "\\d+"))
  #place <- str_extract(files$name[i], "[A-Za-z]+")
        
  AC2 <- range_read(files$id[i], 
            sheet = "master", 
            range = "AC2") %>% colnames()
        
  AD2 <- range_read(files$id[i], 
            sheet = "master", 
            range = "AD2") %>% colnames()
  
  info_sheet <- c(AC2, AD2)
  
  info <- bind_cols(info, info_sheet)
  
  Sys.sleep(1)
        
}

colnames(info) <- files$name
```

```{r}
info <- NULL
for(i in 1:nrow(files)){
  
  i = 18
  
  T2 <- range_read_cells(files$id[i], 
            sheet = "master",
            cell_data = "full",
            range = "T2")
  
  if(nrow(T2) == 0) {
    
    info <- bind_cols(info, "dumb!")
    
  } else {
    
  info_sheet <- T2[[4]][[1]][["userEnteredValue"]][["formulaValue"]]
  
  if(is.null(info_sheet)) {
    
    info <- bind_cols(info, "smarties")
    
  } else {
    
    info <- bind_cols(info, info_sheet)
    
  }
  
  }
  
  Sys.sleep(2)
        
}

colnames(info) <- files$name
```

```{r}

for(i in 1:nrow(files)){
  
  nrows <- as.numeric(nrow(range_read(files$id[i])))
  
K_initialID <- data.frame(form = '=ARRAYFORMULA(
  SUBSTITUTE(
    IF( 
      REGEXMATCH(A2:A, "(Sister|Mother|OtherException|Brother|Bro.|Sœur|Soeur|Madame|Madam)") +
      REGEXMATCH(B2:B, "(Brother|Sister|Ladies|Sœur|Soeur|Madame|Madam)") +
      (ISBLANK(I2:I) * ISBLANK(G2:G)),
      "",
      IF(
        ISBLANK(I2:I),
        G2:G,
        IF(
          LEN(I2:I) >= 3,
          IF(
            ISBLANK(J2:J),
            LEFT(I2:I, 3) & "_" & G2:G,
            LEFT(I2:I, 3) & "_" & LEFT(J2:J, 1) & "_" & G2:G
          ),
          IF(
            LEN(I2:I) = 2,
            IF(
              ISBLANK(J2:J),
              LEFT(I2:I, 2) & "_" & G2:G,
              LEFT(I2:I, 2) & "_" & LEFT(J2:J, 1) & "_" & G2:G
            ),
            IF(
              LEN(I2:I) = 1,
              IF(
                ISBLANK(J2:J),
                LEFT(I2:I, 1) & "_" & G2:G,
                LEFT(I2:I, 1) & "_" & LEFT(J2:J, 1) & "_" & G2:G
              ),
              ""
            )
          )
        )
      )
    ),
    "__", "_"
  )
)')

K_initialID$form <- gs4_formula(K_initialID$form) 

        range_write(files$id[i], 
            K_initialID,
            sheet = "peopleInfo",
            range = "K2",
            col_names = FALSE,
            reformat = FALSE)

}

```

```{r}
#check the sheets to delete against the master
files_1870 <- files %>% rowwise() %>%
  mutate(year = str_extract(name, "\\d+")) %>%
  filter(year == 1870)

for(i in 1:nrow(files)){
 
  i = 1
  
    master_attend <- range_read(files$id[i], 
            sheet = "master") %>%
      select("instID", "instName", "city_orig", "attendingInstID", 
             "attendingChurch", "attendingChurchFrequency",
             "attendingChurchNote")
    
    master_instIDs <- range_read(files$id[i], 
            sheet = "master") %>%
      select("instID", "type", "instName", "city_orig")
    
    master_people <- range_read(files$id[i], 
            sheet = "master") %>%
      select("instID", "instName", "city_orig", "persID", "persName")
    
    attendedChurches <- range_read(files$id[i], 
            sheet = "attendedChurches")
    
    instIDs <- range_read(files$id[i], 
            sheet = "instIDs")
    
    peopleWithInsts <- range_read(files$id[i], 
            sheet = "peopleWithInsts")
    
    column_names <- colnames(master_attend)
    
    for (j in 1:length(column_names)){
      
    one <- master_attend$column_names[j]
    two <- attendedChurches$column_names[j]
    
    setdiff(two, one)
    if (setdiff > 0) {
      
      warning(paste0("Differences in"), files[i], "column",
            attendedChurches$column_names[j])
      
    }
    
    else {
      
      print(paste0("No differences in"), files[i], "column",
            attendedChurches$column_names[j])
    }
    
    }
        
}
```

```{r}
#check the sheets to delete against the master
files_1870 <- files %>% rowwise() %>%
  mutate(year = str_extract(name, "\\d+")) %>%
  filter(year == 1870)

for(i in 1:nrow(files_1870)){
  
    master_attend <- range_read(files_1870$id[i], 
            sheet = "master") %>%
      select("instID", "instName", "city_orig", "attendingInstID", 
             "attendingChurch", "attendingChurchFrequency",
             "attendingChurchNote")
    
    master_instIDs <- range_read(files_1870$id[i], 
            sheet = "master") %>%
      select("instID", "type", "instName", "city_orig")
    
    master_people <- range_read(files_1870$id[i], 
            sheet = "master") %>%
      select("instID", "instName", "city_orig", "persID", "persName")
    
    attendedChurches <- range_read(files_1870$id[i], 
            sheet = "attendedChurches")
    
    instIDs <- range_read(files_1870$id[i], 
            sheet = "instIDs")
    
    peopleWithInsts <- range_read(files_1870$id[i], 
            sheet = "peopleWithInsts")
    
    column_names <- colnames(master_attend)
    
    for (j in 1:length(column_names)){
      
    one <- master_attend[column_names[j]]
    two <- attendedChurches[column_names[j]]
    
    diff <- setdiff(two, one)
    if (nrow(diff) > 0) {
      
      warning(paste0("Differences in "), files_1870$name[i], " column ",
            column_names[j])
      
    }
    
    else {
      
      message <- paste0("No differences in ", files_1870$name[i], " column ", column_names[j])
      print(message)
    }
    
    }
        
}


```
```{r}
nrows <- NULL
info <- NULL

for(i in 1:nrow(files)){
  
  instIDs <- read_sheet(files$id[i],
             "instIDs")
  
  peopleWithInsts <- read_sheet(files$id[i],
             "peopleWithInsts")
  
  attendedChurches <- read_sheet(files$id[i],
              "attendedChurches")

  #print(files$name[i])
  nrows <- c(nrow(instIDs),  nrow(peopleWithInsts),
             nrow(attendedChurches))
  
 # sheet_delete(files$id[i],
 #               name)
  
  
  info <- bind_cols(info, nrows)
}


colnames(info) <- files$id

names  <- info %>% pivot_longer(cols = everything()) %>% 
  filter(value == 0) %>%
  group_by(name) %>%
  summarise(count = n()) %>%
  filter(count == 3) %>%
  distinct(name) %>% pull(name)
```

```{r}
files <- files %>% filter(name != "***TEMPLATE")

info1 <- NULL
info2 <- NULL
info3 <- NULL

for(i in 1:nrow(files)){
 
tryCatch(  
  {
    
  attendedChurches <- range_read(files$id[i],
              sheet = "attendedChurches")
  attendedcolnames <- colnames(attendedChurches)
  attendedChurches <- attendedChurches %>%
              rownames_to_column() %>%
              pivot_longer(!rowname)
  
  peopleWithInsts <- range_read(files$id[i],
              sheet = "peopleWithInsts") 
  peoplecolnames <- colnames(peopleWithInsts)
  peopleWithInsts <- peopleWithInsts %>%
              rownames_to_column() %>%
              pivot_longer(!rowname)
  
  instIDs <- range_read(files$id[i],
              sheet = "instIDs") 
  instcolnames <- colnames(instIDs)
  instIDs <- instIDs %>% 
              rownames_to_column() %>%
              pivot_longer(!rowname)

  master <- range_read(files$id[i],
               sheet = "master") %>%
              rownames_to_column() %>%
              pivot_longer(!rowname, values_transform = as.character)

  df1 <- master %>% filter(name %in% attendedcolnames) %>% 
    full_join(attendedChurches, by = c("rowname", "name"))
  
  df2 <- master %>% filter(name %in% peoplecolnames) %>% 
    full_join(peopleWithInsts, by = c("rowname", "name"))
  
  df3 <- master %>% filter(name %in% instcolnames) %>% 
    full_join(instIDs, by = c("rowname", "name"))
 
  df1_filtered <- df1 %>%
    filter(value.x != value.y) %>%
    mutate(sheet = files$name[i]) %>%
    mutate(rowname = as.numeric(rowname)) %>%
    slice_min(rowname)
  
  df2_filtered <- df2 %>%
    filter(value.x != value.y) %>%
    mutate(sheet = files$name[i]) %>%
    mutate(rowname = as.numeric(rowname)) %>%
    slice_min(rowname)
  
  df3_filtered <- df3 %>%
    filter(value.x != value.y) %>%
    mutate(sheet = files$name[i]) %>%
    mutate(rowname = as.numeric(rowname)) %>%
    slice_min(rowname)

tryCatch(  
  {
    info1 <- bind_rows(info1, df1_filtered)
    info2 <- bind_rows(info2, df2_filtered)
    info3 <- bind_rows(info3, df3_filtered)
  },
  error = function(cond) {
    message("Giving us trouble!")
  }
)
  },
  error = function(cond) {
    message("Check if it has the right sheet names!")
  }
)
  
  }

```

