---
title: "update_formulas"
output: html_document
date: "2025-01-16"
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Importing packages 
library(dplyr)
library(readr)
library(tidyr)
library(stringr)
library(googledrive)
library(googlesheets4)
library(DT)
library(purrr)
library(lubridate)
library(gargle)

#Login to Google
gs4_deauth()
#gs4_auth(token = gargle::secret_read_rds(
#  ".secrets/gs4-token.rds",
#  key = "GOOGLE_DRIVE_KEY"
#))
gs4_auth(cache = ".secrets", email = "schroejh@bc.edu", scope = "https://www.googleapis.com/auth/drive")
drive_auth(token = gs4_token())

#Specify ID for each year folder 
folder_ids <- c("1vsjVWIWOAH1xN8RPvhgmI6ky1vA7CfcJ",
                "145ECofup4M7ZnA1dUF5_pDZN3OWEK1Yb",
                "1gi-k4cgD-XR_AiaSq6J9OPf3OWwkIPCt",
                "1IYkTrGI07fTcjaggY_12V72syNATNSIp",
                "10-NQy1b9lXuXnm5X_FuzYpetI_1PgjOQ",
                "1FbOjmMtKKbgpDou-eyVbhb162RQJMNy-",
                "1LEYANh7PIV9BIC4GpmWByWR4mi2dNtih")

#List all the files in all the folders
files <- lapply(folder_ids, function(folder) {
  drive_ls(as_id(folder))
})
files <- do.call("rbind", files) 
files <- files %>% filter(!(str_detect(name, "TEMPLATE")))

```


```{r}
files <- files %>% filter(name != "***TEMPLATE")

info1 <- NULL

for(i in 1:nrow(files)){

  master <- range_read(files$id[i],
               sheet = "master", 
               range = c("A:K")) %>%
    mutate_all(as.character()) %>%
    mutate(instID = as.character(instID),
           type = as.character(type),
           instName = as.character(instName),
           filename = files$name[i]) %>%
    filter(!is.na(instID))

tryCatch(  
  {
    info1 <- bind_rows(info1, master)
  },
  error = function(cond) {
    message("Giving us trouble!")
  }
)

  
}

getwd()

store <- info1
```

```{r}
# check against each other

files <- files %>% filter(name != "***TEMPLATE")

info1 <- NULL
info2 <- NULL
info3 <- NULL

for(i in 1:nrow(files)){
 
tryCatch(  
  {
    
  attendedChurches <- range_read(files$id[i],
              sheet = "attendedChurches")
  attendedcolnames <- colnames(attendedChurches)
  attendedChurches <- attendedChurches %>%
              rownames_to_column() %>%
              pivot_longer(!rowname)
  
  peopleWithInsts <- range_read(files$id[i],
              sheet = "peopleWithInsts") 
  peoplecolnames <- colnames(peopleWithInsts)
  peopleWithInsts <- peopleWithInsts %>%
              rownames_to_column() %>%
              pivot_longer(!rowname)
  
  instIDs <- range_read(files$id[i],
              sheet = "instIDs") 
  instcolnames <- colnames(instIDs)
  instIDs <- instIDs %>% 
              rownames_to_column() %>%
              pivot_longer(!rowname)

  master <- range_read(files$id[i],
               sheet = "master") %>%
              rownames_to_column() %>%
              pivot_longer(!rowname, values_transform = as.character)

  df1 <- master %>% filter(name %in% attendedcolnames) %>% 
    full_join(attendedChurches, by = c("rowname", "name"))
  
  df2 <- master %>% filter(name %in% peoplecolnames) %>% 
    full_join(peopleWithInsts, by = c("rowname", "name"))
  
  df3 <- master %>% filter(name %in% instcolnames) %>% 
    full_join(instIDs, by = c("rowname", "name"))
 
  df1_filtered <- df1 %>%
    filter(value.x != value.y) %>%
    mutate(sheet = files$name[i]) %>%
    mutate(rowname = as.numeric(rowname)) %>%
    slice_min(rowname)
  
  df2_filtered <- df2 %>%
    filter(value.x != value.y) %>%
    mutate(sheet = files$name[i]) %>%
    mutate(rowname = as.numeric(rowname)) %>%
    slice_min(rowname)
  
  df3_filtered <- df3 %>%
    filter(value.x != value.y) %>%
    mutate(sheet = files$name[i]) %>%
    mutate(rowname = as.numeric(rowname)) %>%
    slice_min(rowname)

tryCatch(  
  {
    info1 <- bind_rows(info1, df1_filtered)
    info2 <- bind_rows(info2, df2_filtered)
    info3 <- bind_rows(info3, df3_filtered)
  },
  error = function(cond) {
    message("Giving us trouble!")
  }
)
  },
  error = function(cond) {
    message("Check if it has the right sheet names!")
  }
)
  
  }

```

```{r}
info1 <- #read_csv('./_data/info_for_later.csv') %>%
  mutate(year = as.numeric(str_extract(sheet_name, "\\d+"))) %>%
  select(instID, instName, year) 

n_inst <- length(unique(info1$instID))

filter_out <- info1 %>% group_by(instID, year) %>% 
  mutate(count = n()) %>% filter(count > 1) %>% pull(instID)
  
different_names <- info1 %>%
  filter(!(instID %in% filter_out), 
         !is.na(instName)) %>%
  group_by(instID) %>%
  mutate(count_ids = n()) %>% ungroup() %>%
  group_by(instID, instName) %>%
  mutate(count_names = n()) %>%
  filter(count_ids != count_names) %>%
  arrange(instID, year) %>%
  mutate(diocese = str_sub(instID, 1, 3))

n_inst_different <- length(unique(different_names$instID)) 

info2 <- info1 %>%
  mutate(year = as.numeric(str_extract(filename, "\\d+"))) %>%
  select(instID, instName, year) 

n_inst <- length(unique(info1$instID))

filter_out <- info2 %>% group_by(instID, year) %>% 
  mutate(count = n()) %>% filter(count > 1) %>% pull(instID)
  
different_names <- info1 %>%
  filter(!(instID %in% filter_out), 
         !is.na(instName)) %>%
  group_by(instID) %>%
  mutate(count_ids = n()) %>% ungroup() %>%
  group_by(instID, instName) %>%
  mutate(count_names = n()) %>%
  filter(count_ids != count_names) %>%
  arrange(instID, year) %>%
  mutate(diocese = str_sub(instID, 1, 3))

summary <- info1 %>% 
  select(filename, instID, city_orig, type) %>%
  filter(type %in% c('church', 'chapel')) %>%
  mutate(year = as.numeric(str_extract(filename, "\\d+")),
         diocese = str_extract(filename, "[A-Za-z]+")) %>%
  filter(!is.na(city_orig)) %>% select(-filename) %>%
  group_by(diocese, city_orig, year) %>% mutate(count = n()) %>%
  ungroup(year) %>% 
  distinct(diocese, city_orig, count) %>%
  mutate(count_of_count = n()) %>%
  filter(count_of_count > 1) %>%
  mutate(combine = paste0(diocese, city_orig))
problems <- unique(summary$combine)

joined <- info1 %>%
  select(filename, instID, city_orig, type) %>%
  filter(type %in% c('church', 'chapel')) %>%
  mutate(year = as.numeric(str_extract(filename, "\\d+")),
         diocese = str_extract(filename, "[A-Za-z]+")) %>%
  filter(!is.na(city_orig)) %>% select(-filename) %>%
  group_by(diocese, city_orig, year) %>% mutate(count = n()) %>%
  select(-instID) %>% mutate(combine = paste0(diocese, city_orig)) %>%
  filter(combine %in% problems) %>% distinct(diocese, city_orig, year, count) %>%
  filter(diocese != "Alton", diocese != "SantaFe", count <= 5) %>%
  arrange(city_orig, year)
  

```

```{r}
info_long <- info %>% pivot_longer(cols = everything())
```

