---
title: "03_explore_person_ids"
output: html_document
date: "2024-11-07"
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(stringr)
library(googledrive)
library(googlesheets4)

gs4_deauth()
gs4_auth(cache = ".secrets", email = "schroejh@bc.edu", scope = "https://www.googleapis.com/auth/drive")
drive_auth(token = gs4_token())

```

```{r}
# Get file ids from folders
folder_ids <- c("1vsjVWIWOAH1xN8RPvhgmI6ky1vA7CfcJ",
    "145ECofup4M7ZnA1dUF5_pDZN3OWEK1Yb",
    "1gi-k4cgD-XR_AiaSq6J9OPf3OWwkIPCt",
    "1IYkTrGI07fTcjaggY_12V72syNATNSIp",
    "10-NQy1b9lXuXnm5X_FuzYpetI_1PgjOQ",
    "1FbOjmMtKKbgpDou-eyVbhb162RQJMNy-",
    "1LEYANh7PIV9BIC4GpmWByWR4mi2dNtih")

files <- lapply(folder_ids, function(folder) {
  drive_ls(as_id(folder))
})
files <- do.call("rbind", files)
```

```{r}
# Get the peopleInfo sheet from each file
sheet <- "master"
lookup <- c(persTitle = "personTitle", persTitle = "title")

time1 <- Sys.time()
peopleInfos <- data.frame("instID" = NA, "type" = NA, "instName" = NA, "language" = NA, "instNote" = NA, "placeName" = NA, "region" = NA, "county_orig" = NA, "county_reg"   = NA, "city_orig" = NA, "city_reg" = NA, "state_orig" = NA, "state_reg" = NA, "latitude" = NA, "longitude" = NA, "attendingInstID" = NA, "attendingChurch" = NA, "attendingChurchFrequency" = NA, "attendingChurchNote" = NA, "persID" = NA, "persTitle" = NA, "persName" = NA, "persSuffix" = NA, "persRole" = NA, "persNote"      = NA, "memberType" = NA, "member" = NA, "affiliated" = NA, "place" = NA, "year" = NA, "city_reg" = NA, "state_reg" = NA)

for (i in 1:nrow(files)) {
   
  tryCatch(
    {
    sheet_peopleInfo <- read_sheet(files$id[i], sheet = sheet) %>%
       filter(!is.na(persName)) %>%
       mutate(place = str_extract(files$name[i], "[A-Za-z]+"),
              year = str_extract(files$name[i], "\\d+")) %>%
      rename(any_of(lookup)) %>%
      mutate(across(everything(), as.character),
             city_reg = NA, state_reg = NA)
  
     if(nrow(sheet_peopleInfo) != 0) {
      peopleInfos <- bind_rows(sheet_peopleInfo, peopleInfos)
      }
     else {
       next
      }
  },
  error = function(e) {
    message("Something didn't work right!")
  })
  
}

time2 <- Sys.time()
print(time2-time1)
#write_csv(peopleInfos, "peopleInfos.csv")
#getwd()
```

```{r}
people <- do.call(rbind.data.frame, peopleInfos)
rownames(people) <- NULL
people %>% count()

people <- people %>% distinct(persName, place, persTitle) 
# 4966 people

# Break out middle names more
# Fix imposing the last names as first names (safe assummption that nobody has the same first and last name)
people <- people %>% separate(persName, c("first_name", "last_name"), sep=" (?=[^ ]*$)") %>%
  mutate(last_name = ifelse(is.na(last_name), first_name, last_name)) 

#people <- people %>% filter(last_name != "teacher|teachers|Priests")
#people %>% count()
# removing some non-specific names

people %>% count()
# 4441 people looking at uniques only

people %>% group_by(last_name) %>% mutate(count_name = n(), unique_name = ifelse(count_name == 1, TRUE, FALSE)) %>%
  ungroup() %>% group_by(unique_name) %>%
  mutate(percent = round(n()/1455	 * 100, 2))
# 46.477% duplicate last names

people %>% mutate(first_last = paste0(substr(first_name, 1, 1), "_", last_name)) %>%
  group_by(first_last) %>% mutate(count_name = n(), unique_name = ifelse(count_name == 1, TRUE, FALSE)) %>%
  ungroup() %>% group_by(unique_name) %>%
  mutate(percent = round(n()/1455	 * 100, 2))
# 21.9% duplicate first initial and last name


test <- people %>% mutate(first_name = gsub("[[:punct:][:blank:]]+", "", first_name)) %>%
  mutate(first_last = case_when(
    nchar(first_name) >= 4 ~ paste0(substr(first_name, 1, 3), "_", last_name),
    nchar(first_name) == 2 ~ paste0(substr(first_name, 1, 2), "_", last_name),
    nchar(first_name) == 1 ~ paste0(substr(first_name, 1, 1), "_", last_name),
    nchar(first_name) == 0 & !is.na(persTitle) ~ paste0(substr(persTitle, 1, 3), "_", last_name),
    .default = "HELP!"
  )) %>% mutate(year = 1869)

hi <- test %>%
  group_by(first_last, place) %>% mutate(count_name = n(), unique_name = ifelse(count_name == 1, TRUE, FALSE)) %>%
  ungroup() %>% group_by(unique_name) %>%
  mutate(percent = round(n()/1455	 * 100, 2)) #%>% arrange(-count_name)

year = 1870

files <- list.files(paste0("../data/", year, "/"))
sheet <- "peopleInfo"

lookup <- c(persTitle = "personTitle", persTitle = "title")

peopleInfos <- list()
# Having an issue filtering out NAs
for (i in 1:length(files)) {
  print(files[i])
  sheet_peopleInfo <- read_excel(paste0("../data/", year, "/", files[i]), sheet = sheet) %>% filter(!is.na(persName)) %>%
    mutate(place = str_squish(sub(year, ".xlsx", files[i]))) %>%
    rename(any_of(lookup)) %>%
    select(persName, place, persTitle, persRole)
  
  peopleInfos[[files[i]]] <- sheet_peopleInfo
}

people <- do.call(rbind.data.frame, peopleInfos)
rownames(people) <- NULL
people %>% count()

people <- people %>% distinct(persName, place, persTitle) 
# 4966 people

# create first, middle, and last names columns
people <- people %>% 
  mutate(persName_clean = tolower(str_replace_all(persName, "[[:punct:]]", ""))) %>%
  mutate(persName_clean = str_replace_all(persName_clean, 
                                            "\\b(von|de|la|der|van)\\s+(\\w+)", 
                                            "\\1-\\2")) %>%
  separate(persName_clean, c("first_middle", "last_name"), sep=" (?=[^ ]*$)",
           remove = FALSE) %>%
  mutate(last_name = str_squish(ifelse(is.na(last_name), first_middle, last_name)),
         first_middle = str_squish(ifelse(first_middle == last_name, NA, first_middle))) %>%
  separate(first_middle, c("first_name", "middle_name"),  sep = " ", extra = "merge", fill = "right") %>% mutate_all(na_if,"")

#people <- people %>% filter(last_name != "teacher|teachers|Priests")
#people %>% count()
# removing some non-specific names

n_people <- nrow(people)
# 4441 people looking at uniques only

people %>% group_by(last_name) %>% mutate(count_name = n(), unique_name = ifelse(count_name == 1, TRUE, FALSE)) %>%
  ungroup() %>% group_by(unique_name) %>%
  mutate(percent = round(n()/n_people	 * 100, 2))
# 46.477% duplicate last names

people %>% mutate(first_last = paste0(substr(first_name, 1, 1), "_", last_name)) %>%
  group_by(first_last) %>% mutate(count_name = n(), unique_name = ifelse(count_name == 1, TRUE, FALSE)) %>%
  ungroup() %>% group_by(unique_name) %>%
  mutate(percent = round(n()/n_people	 * 100, 2))
# 21.9% duplicate first initial and last name

test <- people %>% 
  mutate(pers_id = case_when(
    (nchar(first_name) >= 3 & !is.na(middle_name)) ~ paste0(substr(first_name, 1, 3), "_", substr(middle_name, 1, 1),  "_", last_name),
    (nchar(first_name) >= 3 & is.na(middle_name)) ~ paste0(substr(first_name, 1, 3), "_", last_name),
    (nchar(first_name) == 2 & !is.na(middle_name)) ~ paste0(substr(first_name, 1, 2), "_", substr(middle_name, 1, 1), "_", last_name),
    (nchar(first_name) == 2 & is.na(middle_name)) ~ paste0(substr(first_name, 1, 2), "_", last_name),
    (nchar(first_name) == 1 & !is.na(middle_name)) ~ paste0(substr(first_name, 1, 1), "_", substr(middle_name, 1, 1), "_", last_name),
    (nchar(first_name) == 1 & is.na(middle_name)) ~ paste0(substr(first_name, 1, 1), "_", last_name),
    is.na(first_name) & !is.na(persTitle) ~ paste0(persTitle, "_", last_name),
    is.na(first_name) & is.na(persTitle) ~ paste0("none_", last_name),
    .default = "HELP!"
  )) %>% mutate(year = year)

test_1870 <- test %>%
  group_by(pers_id) %>% mutate(
    count_name = n(), 
    unique_name = ifelse(count_name == 1, TRUE, FALSE)) %>%
  group_by(pers_id, place) %>%
    mutate(count_name_in_place = n(), 
    unique_name_in_place = ifelse(count_name_in_place == 1, TRUE, FALSE)) %>%
  ungroup() #%>% group_by(unique_name) %>%
  #mutate(percent_name = round(n()/n_people * 100, 2)) %>% 
  #group_by(unique_name_in_place) %>%
  #mutate(percent_name_in_place = round(n()/n_people	* 100, 2)) %>% arrange(pers_id) #%>%
#  filter(unique_name_in_place == TRUE, unique_name == FALSE,
#         !(str_detect(persName, "Brother*|brother*|Sister*|sister*|under|Under")),
#         !is.na(persName_clean))
# try for 95 percent unique (within year) - there could be two within the same 
```

```{r}
library(reshape2)

test_combined <- rbind(test_1869, test_1870)

uniques <- test_combined %>%
  select(pers_id, year) %>% group_by(pers_id, year) %>%
  mutate(count = n()) %>% 
  distinct(pers_id, year, count) %>%
  group_by(pers_id) %>% pivot_wider(id_cols = pers_id,
                                       names_from = year, values_from = count, values_fill = 0) %>%
  mutate(sum = sum(`1869` + `1870`)) #%>%
  group_by(sum_overall) %>% summarise(count = n())
  
## Boston test case
# write formula in google sheets
  # comment up the personid doc
 # a_jourdan/a_jourdon prob the same when they're 
```


```{r}
peopleInfos %>% filter(!is.na(`...79`))

colnames(peopleInfos)
```

