name: Rebuild and Deploy Static Site

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every 24 hours at midnight
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          pandoc \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libpng-dev \
          libtiff5-dev \
          libjpeg-dev

    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/R
        key: ${{ runner.os }}-r-${{ hashFiles('**/*.R', '**/*.Rmd') }}
        restore-keys: |
          ${{ runner.os }}-r-

    - name: Install R Packages
      run: |
        R -e "options(repos = 'https://cloud.r-project.org')"
        R -e "install.packages(c('rmarkdown', 'knitr', 'dplyr', 'readr', 'tidyr', 'stringr', 'googledrive', 'googlesheets4', 'DT', 'jsonlite', 'purrr', 'lubridate', 'openssl'))"

    - name: Check Pandoc Version
      run: pandoc --version

    - name: Knit R Markdown
      env:
        CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
      run: |
        echo "Secret starts with: ${CERTIFICATE_BASE64:0:5}"
        Rscript -e "Sys.setenv(CERTIFICATE_BASE64 = Sys.getenv('CERTIFICATE_BASE64'))"
        Rscript -e "rmarkdown::render_site()"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_docs  # Change to your output directory
