name: Rebuild and Deploy Static Site

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every 24 hours at midnight
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        R -e "install.packages('rmarkdown')"
        R -e "install.packages('knitr')"
        R -e "install.packages('tidyverse')"
        R -e "install.packages('stringr')"
        R -e "install.packages('googledrive')"
        R -e "install.packages('googlesheets4')"
        R -e "install.packages('DT')"
        R -e "install.packages('jsonlite')"

    - name: Build site
      run: |
        Rscript -e "rmarkdown::render_site()"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_docs  # Change to your output directory
